apiVersion : apps/v1
kind: Deployment
metadata:
  name: "yiha-573d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "yiha-573d"
  template:
    metadata:
      labels:
        app: "yiha-573d"
    spec:
      containers:
        - name: "yiha-573d"
          image: "tessy.azurecr.io/yiha"
          ports:
          - containerPort: 80