apiVersion: v1
kind: Service
metadata:
    name: "yiha-0e58"
    labels:
        app: "yiha-0e58"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "yiha-0e58"