on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tessy.azurecr.io
        username: ${{ secrets.acr_tessy_username }}
        password: ${{ secrets.acr_tessy_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tessy.azurecr.io/yiha:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tessy.azurecr.io/yiha:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_yiha_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep yihaa722 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace yihaa722`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: yihaa722
        container-registry-url: tessy.azurecr.io
        container-registry-username: ${{ secrets.acr_tessy_username }}
        container-registry-password: ${{ secrets.acr_tessy_password }}
        secret-name: yihadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: yihaa722
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          tessy.azurecr.io/yiha:${{ github.sha }}
        imagepullsecrets: |
          yihadockerauth
